Fall 2016 cleanup.

diff --git a/bin/copy_music b/bin/copy_music
--- a/bin/copy_music
+++ b/bin/copy_music
@@ -16,9 +16,9 @@ EOF
 
 
 if [ -z "$1" ]; then
-	echo "ERROR: Bad arguments"
+  echo "ERROR: Bad arguments"
     usage_help
-	exit 1
+  exit 1
 fi
 
 
